services:
  postgres:
    build: ./postgres
    container_name: brb-postgres
    environment:
      POSTGRES_DB: brb_chatbot
      POSTGRES_USER: brb_user
      POSTGRES_PASSWORD: brb_password123
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - brb_network

  qdrant:
    image: qdrant/qdrant:v1.18.0 # Eng so'nggi barqaror versiya
    container_name: brb-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant/data:/qdrant/storage # Endi fayllar rostdan ham VS Code dagi papkaga tushadi
    restart: unless-stopped
    networks:
      - brb_network

  chat-app:
    build: ./app
    container_name: brb-bank-chatbot
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8080 --reload
    environment:
      - VLLM_URL=http://host.docker.internal:8050/v1
      - QDRANT_HOST=http://qdrant:6333
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=brb_chatbot
      - POSTGRES_USER=brb_user
      - POSTGRES_PASSWORD=brb_password123
      - HF_TOKEN=YOUR_HUGGINGFACE_TOKEN_HERE
    depends_on:
      - postgres
      - qdrant # Chat-app ishlashidan oldin Qdrant yongan bo'lishini ta'minlaydi
    restart: unless-stopped
    networks:
      - brb_network

networks:
  brb_network:
    external: true